name: kas-test

# Run on changes to master
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

#      - uses: xsavikx/artifact-exists-action@v0
#        id: check_download_artifact
#        with:
#          name: 'download'

#      - name: create download dir
#        #if: steps.check_download_artifact.exists == 'true'
#        run: mkdir -p build/downloads

#      - uses: actions/download-artifact@v3
#        #if: steps.check_download_artifact.exists == 'true'
#        with:
#          name: download
#          path: build/downloads

#      - uses: xsavikx/artifact-exists-action@v0
#        id: check_sstate_artifact
#        with:
#          name: 'sstate'
       
#      - name: create sstate dir
#        #if: steps.check_sstate_artifact.exists == 'true'
#        run: mkdir -p build/sstate-cache

#      - uses: actions/download-artifact@v3
#        #if: steps.check_sstate_artifact.exists == 'true'
#        with:
#          name: sstate
#          path: sstate.tar.xz

#      - name: extract sstate tarball
#        #if: steps.check_sstate_artifact.exists == 'true'
#        run: |
#          tar -xJf sstate.tar.xz -C build/sstate-cache/

      - name: Build qemu image
        run: |
            pwd
            /bin/ls -lR
            /usr/bin/wget "https://raw.githubusercontent.com/siemens/kas/master/kas-container" -O kas-container
            /bin/bash kas-container build kas-base.yml

      - name: create sstate tarball
        run: |
            tar -cJf sstate.tar.xz -C build/sstate-cache/ .

      - name: Upload SSTATE to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3-sstate
        with:
            aws_bucket: kas-test
            source_dir: '.'
            aws_key_id: ${{secrets.AWS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

