name: kas-test

# Run on changes to master
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
       
      - name: Build qemu image
        run: |
            pwd
            /bin/ls -lR
            /usr/bin/wget "https://raw.githubusercontent.com/siemens/kas/master/kas-container" -O kas-container
            /bin/bash kas-container build kas-base.yml
      
      - uses: actions/upload-artifact@v3 
        with:
          name: sstate
          path: build/tmp/sstate-cache


