name: kas-test

# Run on changes to master
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    container:
       image: ghcr.io/siemens/kas/kas:latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build meta-raspberrypi
        run: |
            cd $BUILD_DIR
            kas build meta-rpi2.yml
